#!/usr/bin/env bash
# a script to transfer a file from client to remote server
#
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
file="$1"
ip="$2"
user="$3"
key="$4"

if [ $# -eq 4 ]; then
	scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
	echo -e "Usage: 0-trtansfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
